// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import '../features/timeline/timeline_page_test.dart' as features_timeline_timeline_page;

void main(List<String> args) {
  features_timeline_timeline_page.main(args);
}
