name: Build

on: [push, pull_request]

jobs:
  build_app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: ["dev", "beta"]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
