name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: ["dev"]
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email polanski.tomek@gmail.com
          git config --global user.name tomaszpolanski
          git status
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/tomaszpolanski/healfy.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
